#= require jquery
#= require active_admin/jquery_ui
#= require jquery_ujs
#= require tinymce
#= require select2-full
#= require_self
#= require active_admin/lib/batch_actions
#= require active_admin/lib/checkbox-toggler
#= require active_admin/lib/dropdown-menu
#= require active_admin/lib/flash
#= require active_admin/lib/has_many
#= require active_admin/lib/per_page
#= require active_admin/lib/table-checkbox-toggler
#= require active_admin/ext/jquery-ui
#= require active_admin/ext/jquery
#= require active_admin/initializers/batch_actions
#= require active_admin/initializers/datepicker
#= require active_admin/initializers/filters
#= require_tree ./lib
#= require_tree ./initializers
#= require_tree ./vendors

window.ActiveAdmin = {}
